name: Deploy to Production

on:
    workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Generate env from secrets
              run: |
                  SECRETS="${{ secrets.NGOBROL_ZONE_GCP_ENV_PRODUCTION }}"
                  echo "$SECRETS" | tr ';' '\n' >> .env

            - id: "auth"
              uses: "google-github-actions/auth@v2"
              with:
                  credentials_json: "${{ secrets.NGOBROL_ZONE_GCP_SA_KEY }}"

            - name: "Set up Cloud SDK"
              uses: "google-github-actions/setup-gcloud@v2"

            - name: Deploy to App Engine
              run: |
                  gcloud app deploy production.yaml
